name: Test frontend

on:
  push:
    paths:
      - "src/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Test with jest
        run: |
          yarn test
